#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-glances
Version  : 2.11
Release  : 23
URL      : https://github.com/nicolargo/glances/archive/v2.11.tar.gz
Source0  : https://github.com/nicolargo/glances/archive/v2.11.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: deprecated-glances-bin = %{version}-%{release}
Requires: deprecated-glances-license = %{version}-%{release}
Requires: deprecated-glances-man = %{version}-%{release}
Requires: deprecated-glances-python = %{version}-%{release}
Requires: psutil
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : psutil
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
===============================
Glances - An eye on your system
===============================

%package bin
Summary: bin components for the deprecated-glances package.
Group: Binaries
Requires: deprecated-glances-license = %{version}-%{release}

%description bin
bin components for the deprecated-glances package.


%package doc
Summary: doc components for the deprecated-glances package.
Group: Documentation
Requires: deprecated-glances-man = %{version}-%{release}

%description doc
doc components for the deprecated-glances package.


%package legacypython
Summary: legacypython components for the deprecated-glances package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-glances package.


%package license
Summary: license components for the deprecated-glances package.
Group: Default

%description license
license components for the deprecated-glances package.


%package man
Summary: man components for the deprecated-glances package.
Group: Default

%description man
man components for the deprecated-glances package.


%package python
Summary: python components for the deprecated-glances package.
Group: Default

%description python
python components for the deprecated-glances package.


%prep
%setup -q -n glances-2.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554341364
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-glances
cp COPYING %{buildroot}/usr/share/package-licenses/deprecated-glances/COPYING
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/glances

%files doc
%defattr(0644,root,root,0755)
%exclude /usr/share/doc/glances/AUTHORS
%exclude /usr/share/doc/glances/CONTRIBUTING.md
%exclude /usr/share/doc/glances/COPYING
%exclude /usr/share/doc/glances/NEWS
%exclude /usr/share/doc/glances/README.rst
%exclude /usr/share/doc/glances/glances.conf

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-glances/COPYING

%files man
%defattr(0644,root,root,0755)
%exclude /usr/share/man/man1/glances.1

%files python
%defattr(-,root,root,-)
